pub enum Keyword {
  Break,
  Case,
  Catch,
  Class,
  Const,
  Continue,
  Default,
  Delete,
  Do,
  Else,
  Enum,
  Export,
  Extends,
  Finally,
  For,
  Function,
  If,
  Import,
  In,
  Instanceof,
  Let,
  New,
  Return,
  Super,
  Switch,
  This,
  Throw,
  Try,
  Typeof,
  Var,
  Void,
  While,
  With
}

pub fn value_of_keyword(key: Keyword) -> &'static str {
  match key {
    Keyword::Break => "break",
    Keyword::Case => "case",
    Keyword::Catch => "catch",
    Keyword::Class => "class",
    Keyword::Const => "const",
    Keyword::Continue => "continue",
    Keyword::Default => "default",
    Keyword::Delete => "delete",
    Keyword::Do => "do",
    Keyword::Else => "else",
    Keyword::Enum => "enum",
    Keyword::Export => "export",
    Keyword::Extends => "extends",
    Keyword::Finally => "finally",
    Keyword::For => "for",
    Keyword::Function => "function",
    Keyword::If => "if",
    Keyword::Import => "import",
    Keyword::In => "in",
    Keyword::Instanceof => "instanceof",
    Keyword::Let => "let",
    Keyword::New => "new",
    Keyword::Return => "return",
    Keyword::Super => "super",
    Keyword::Switch => "switch",
    Keyword::This => "this",
    Keyword::Throw => "throw",
    Keyword::Try => "try",
    Keyword::Typeof => "typeof",
    Keyword::Var => "var",
    Keyword::Void => "void",
    Keyword::While => "while",
    Keyword::With => "with",
  }
}

pub fn keyword_from_str(s: &str) -> Option<Keyword> {
  match s {
    "break" => Some(Keyword::Break),
    "case" => Some(Keyword::Case),
    "catch" => Some(Keyword::Catch),
    "class" => Some(Keyword::Class),
    "const" => Some(Keyword::Const),
    "continue" => Some(Keyword::Continue),
    "default" => Some(Keyword::Default),
    "delete" => Some(Keyword::Delete),
    "do" => Some(Keyword::Do),
    "else" => Some(Keyword::Else),
    "enum" => Some(Keyword::Enum),
    "export" => Some(Keyword::Export),
    "extends" => Some(Keyword::Extends),
    "finally" => Some(Keyword::Finally),
    "for" => Some(Keyword::For),
    "function" => Some(Keyword::Function),
    "if" => Some(Keyword::If),
    "import" => Some(Keyword::Import),
    "in" => Some(Keyword::In),
    "instanceof" => Some(Keyword::Instanceof),
    "let" => Some(Keyword::Let),
    "new" => Some(Keyword::New),
    "return" => Some(Keyword::Return),
    "super" => Some(Keyword::Super),
    "switch" => Some(Keyword::Switch),
    "this" => Some(Keyword::This),
    "throw" => Some(Keyword::Throw),
    "try" => Some(Keyword::Try),
    "typeof" => Some(Keyword::Typeof),
    "var" => Some(Keyword::Var),
    "void" => Some(Keyword::Void),
    "while" => Some(Keyword::While),
    "with" => Some(Keyword::With),
    _ => None,
  }
}

pub fn is_keyword(s: &str) -> bool {
  keyword_from_str(s).is_some()
}

pub enum Denotation {
  BraceL,
  BraceR,
  ParenL,
  ParenR,
  BracketL,
  BracketR,
  Dot,
  Semi,
  Comma,
  LT,
  GT,
  LE,
  GE,
  Eq,
  NotEq,
  EqStrict,
  NotEqStrict,
  Add,
  Sub,
  Mul,
  Div,
  Mod,
  Inc,
  Dec,
  SHL,
  SAR,
  SHR,
  BitAnd,
  BitOr,
  BitXor,
  Not,
  BitNot,
  And,
  Or,
  Conditional,
  Colon,
  Assign,
  AssignAdd,
  AssignSub,
  AssignMul,
  AssignDiv,
  AssignMod,
  AssignSHL,
  AssignSAR,
  AssignSHR,
  AssignBitAnd,
  AssignBitOr,
  AssignBitXor,
}

pub fn value_of_annotation(denotation: Denotation) -> &'static str {
  match denotation {
    Denotation::BraceL => "{",
    Denotation::BraceR => "}",
    Denotation::ParenL => "(",
    Denotation::ParenR => ")",
    Denotation::BracketL => "[",
    Denotation::BracketR => "]",
    Denotation::Dot => ".",
    Denotation::Semi => ";",
    Denotation::Comma => ",",
    Denotation::LT => "<",
    Denotation::GT => ">",
    Denotation::LE => "<=",
    Denotation::GE => ">=",
    Denotation::Eq => "==",
    Denotation::NotEq => "!=",
    Denotation::EqStrict => "===",
    Denotation::NotEqStrict => "!==",
    Denotation::Add => "+",
    Denotation::Sub => "-",
    Denotation::Mul => "*",
    Denotation::Div => "/",
    Denotation::Mod => "%",
    Denotation::Inc => "++",
    Denotation::Dec => "--",
    Denotation::SHL => "<<",
    Denotation::SAR => ">>",
    Denotation::SHR => ">>>",
    Denotation::BitAnd => "&",
    Denotation::BitOr => "|",
    Denotation::BitXor => "^",
    Denotation::Not => "!",
    Denotation::BitNot => "~",
    Denotation::And => "&&",
    Denotation::Or => "||",
    Denotation::Conditional => "?",
    Denotation::Colon => ":",
    Denotation::Assign => "=",
    Denotation::AssignAdd => "+=",
    Denotation::AssignSub => "-=",
    Denotation::AssignMul => "*=",
    Denotation::AssignDiv => "/=",
    Denotation::AssignMod => "%=",
    Denotation::AssignSHL => "<<=",
    Denotation::AssignSAR => ">>=",
    Denotation::AssignSHR => ">>>=",
    Denotation::AssignBitAnd => "&=",
    Denotation::AssignBitOr => "|=",
    Denotation::AssignBitXor => "^=",
  }
}