[package]
name = "jsmoteur"
version = "0.1.0"
authors = ["liuyize <liuyize@bytedance.com>"]
edition = "2018"

[lib]
name = "lib"
path = "src/lib/index.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
